set(IFW_VERSION_STR "4.11.0")
set(IFW_VERSION "0x041100")
set(IFW_VERSION_WIN32 "4,11,0,0")
set(IFW_VERSION_STR_WIN32 "${IFW_VERSION_STR}\\0")
set(IFW_REPOSITORY_FORMAT_VERSION "1.0.0")
set(IFW_CACHE_FORMAT_VERSION "1.2.0")

execute_process(COMMAND git rev-list --abbrev-commit -n1 HEAD OUTPUT_VARIABLE GIT_SHA1)
set(IFW_COMPILE_DEFINITIONS
        NOMINMAX
        QT_NO_CAST_FROM_ASCII
        QT_STRICT_ITERATORS
        QT_USE_QSTRINGBUILDER
        "_GIT_SHA1_=${GIT_SHA1} "
        "IFW_VERSION_STR=${IFW_VERSION_STR}"
        "IFW_VERSION=${IFW_VERSION}"
        "IFW_VERSION_STR_WIN32=${IFW_VERSION_STR_WIN32}"
        "IFW_VERSION_WIN32=${IFW_VERSION_WIN32}"
        "IFW_REPOSITORY_FORMAT_VERSION=${IFW_REPOSITORY_FORMAT_VERSION}"
        "IFW_CACHE_FORMAT_VERSION=${IFW_CACHE_FORMAT_VERSION}")
